import { Card, Layout, Link, Page } from "@shopify/polaris";
import Head from "next/head";

export default function Home() {
    return (
        <Page>
            <Head>
                <title>Outcast Shopify App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Layout.Section>
                    <Card sectioned title="Welcome" actions={[{ content: "Settings", url: "/settings"}]}>Outcast Index.js</Card>
                </Layout.Section>
            </Layout>
        </Page>
    );
}
