import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Button, Card, Layout, Page, Spinner } from "@shopify/polaris";
import Head from "next/head";

import { userLoggedInFetch } from "@lib/fetch";
import { useAppBridge } from "@shopify/app-bridge-react";
import { Redirect } from "@shopify/app-bridge/actions";

export default function Home() {
    const router = useRouter();
    const app = useAppBridge();
    const fetchFunction = userLoggedInFetch();

    const [loading, setLoading] = useState(router.query?.id ? true : false);

    useEffect(() => {
        if (router.query?.id) {
            convertToDraft();
        }
    }, []);

    const convertToDraft = async () => {
        try {
            const response = await fetchFunction(`/api/admin/convert?id=${router.query?.id}`).then((res) => {
                if (!res) {
                    return null;
                }
                return res?.json()
            });

            console.log({ response })
            
        } catch (error) {
            console.warn(error);
        }
    }

    const navigateToAbandonedCheckouts = () => {
        const redirect = Redirect.create(app);
        redirect.dispatch(Redirect.Action.ADMIN_PATH, "/checkouts");
    }

    if (router.query?.id) {
        if (loading) {
            return (
                <Page>
                    <Layout>
                        <Layout.Section>
                            <Card
                                sectioned
                                title="Creating draft order..."
                            >
                                <Spinner />
                            </Card>
                        </Layout.Section>
                    </Layout>
                </Page>
            )
        }

        return (
            <Page>
                <Layout>
                    <Layout.Section>
                        <Card
                            sectioned
                            title="Redirecting to draft order..."
                        >
                            <Spinner />
                        </Card>
                    </Layout.Section>
                </Layout>
            </Page>
        )
    }

    return (
        <Page>
            <Head>
                <title>Outcast Shopify App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <Layout.Section>
                    <Card
                        sectioned
                        title="First, select an abandoned checkout"
                        //actions={[{ content: "Settings", url: "/settings"}]}
                    >
                        Navigate to <Button plain onClick={navigateToAbandonedCheckouts}>Orders &rarr; Abandoned checkouts</Button>. Select an abandoned checkout and then click: More
                        actions &rarr; Convert to draft order.
                    </Card>
                </Layout.Section>
            </Layout>
        </Page>
    );
}
